### ISSUE TITLE
How are changes pushed to hub.docker.com?

### ISSUE THREAD

**Issue by cmorganBE** [repoocaj/ses#2]
Hi Jeff.

I see that the docker hub images haven't been updated. Do you have this repo connected to hub.docker.com or is that update process manual?

Chris

**Comment by repoocaj** [comment]
That update is a manual process at the moment.

I'll kick off a build locally and shove up an update today.

**Comment by repoocaj** [comment]
Update has been pushed:

https://cloud.docker.com/repository/docker/repoocaj/ses/tags
